"""empty message

Revision ID: d3a78e69f06f
Revises: db781cdba767
Create Date: 2025-09-29 15:01:01.384692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a78e69f06f'
down_revision: Union[str, Sequence[str], None] = 'db781cdba767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'audio_gtzan', ['id'])
    op.create_unique_constraint(None, 'audio_speech_commands', ['id'])
    op.create_unique_constraint(None, 'audio_urban', ['id'])
    op.create_unique_constraint(None, 'image_cifar', ['id'])
    op.create_unique_constraint(None, 'image_fashion_mnist', ['id'])
    op.create_unique_constraint(None, 'image_mnist', ['id'])
    op.create_unique_constraint(None, 'text_ag_news', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'text_ag_news', type_='unique')
    op.drop_constraint(None, 'image_mnist', type_='unique')
    op.drop_constraint(None, 'image_fashion_mnist', type_='unique')
    op.drop_constraint(None, 'image_cifar', type_='unique')
    op.drop_constraint(None, 'audio_urban', type_='unique')
    op.drop_constraint(None, 'audio_speech_commands', type_='unique')
    op.drop_constraint(None, 'audio_gtzan', type_='unique')
    # ### end Alembic commands ###
